name = "enet_enc28j60"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

[[depends-on]]
enet = "^1.0"

[[pins]]
enet = { url='https://github.com/reznikmm/ada-enet' }
